# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.CharField(max_length=255)),
                ('Tname', models.CharField(max_length=255)),
                ('Tcontact', models.CharField(max_length=255)),
                ('Tarea1', models.CharField(max_length=255)),
                ('Tarea2', models.CharField(max_length=255)),
                ('Tgender', models.CharField(max_length=255)),
                ('Tmedium', models.CharField(max_length=255)),
            ],
        ),
    ]
