# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0004_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='Tsubject',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
