# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0005_teachers_tsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spost', models.CharField(max_length=225)),
                ('SpostedBy', models.CharField(max_length=225)),
                ('SpostTime', models.CharField(max_length=225)),
                ('SofferdMoney', models.CharField(max_length=225)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Sid',
            new_name='Sname',
        ),
    ]
