# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0006_auto_20180814_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='Ssubject',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Sarea',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Sgender',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Smedium',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Smoney',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Ssubject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpost',
            name='Spost',
            field=models.CharField(max_length=300),
        ),
    ]
