# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachme', '0007_auto_20180814_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Scontact',
            field=models.CharField(default=999, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpost',
            name='SpostTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
